apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  labels:
    app.kubernetes.io/part-of: simple-app
    supplychain/demo: test01
  name: simple-app
spec:
  source:
    git:
      ref:
        branch: main
      url: https://github.com/tsalm-pivotal/spring-boot-hello-world.git

